# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTR3PFVZmD6CupkDGHHyB6mmJBFCdStI
"""

!pip install -q google-genai gradio

import os
import getpass

os.environ["GEMINI_API_KEY"] = getpass.getpass("Enter your Gemini API Key: ")

from google import genai

client = genai.Client(
    api_key=os.environ["GEMINI_API_KEY"]
)

def study_assistant(topic, action, question):

    if action == "Explain":

        prompt = f"""
Explain this topic like a teacher.

Topic:
{topic}

Use:
- Simple language
- Examples
- Important points
"""

    elif action == "Summarize":

        prompt = f"""
Summarize the following study material.

Material:
{topic}

Give:
- Key points
- Important concepts
- Short summary
"""

    elif action == "Quiz":

        prompt = f"""
Create a quiz based on this topic:

{topic}

Create 5 questions.

Give the answers at the end.
"""

    else:

        prompt = f"""
You are a helpful AI study assistant.

Study topic:
{topic}

Student question:
{question}

Give a clear and easy-to-understand answer.
"""

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    return response.text

answer = study_assistant(
    "Normalization in DBMS",
    "Explain",
    ""
)

print(answer)

import gradio as gr

with gr.Blocks(title="Interactive Study Assistant") as app:

    gr.Markdown("# 📚 Interactive Study Assistant")
    gr.Markdown(
        "Learn, summarize, quiz yourself and ask questions using Gemini AI."
    )

    topic = gr.Textbox(
        label="Study Topic / Notes",
        placeholder="Example: Normalization in DBMS"
    )

    action = gr.Dropdown(
        [
            "Explain",
            "Summarize",
            "Quiz",
            "Ask Question"
        ],
        value="Explain",
        label="Choose Action"
    )

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What is 3NF?"
    )

    submit = gr.Button("🤖 Ask Gemini")

    output = gr.Markdown(
        label="AI Response"
    )

    submit.click(
        fn=study_assistant,
        inputs=[topic, action, question],
        outputs=output
    )

app.launch(share=True)